//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalaryCalculator.Desktop.Ressources.Errors {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SalaryCalculator.Desktop.Ressources.Errors.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Hourly Fee.
        /// </summary>
        internal static string InvalidHourlyFee {
            get {
                return ResourceManager.GetString("InvalidHourlyFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Month.
        /// </summary>
        internal static string InvalidMonth {
            get {
                return ResourceManager.GetString("InvalidMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid configuration was given..
        /// </summary>
        internal static string InvalidMonthConfiguration {
            get {
                return ResourceManager.GetString("InvalidMonthConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Worked Hours.
        /// </summary>
        internal static string InvalidWorkedHours {
            get {
                return ResourceManager.GetString("InvalidWorkedHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hourly fee is missing..
        /// </summary>
        internal static string MissingHourlyFee {
            get {
                return ResourceManager.GetString("MissingHourlyFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worked hours count is missing..
        /// </summary>
        internal static string MissingWorkedHours {
            get {
                return ResourceManager.GetString("MissingWorkedHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported error type, error type is:.
        /// </summary>
        internal static string NotSupportedExceptionType {
            get {
                return ResourceManager.GetString("NotSupportedExceptionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No message found for the error. Error Type is:.
        /// </summary>
        internal static string NotTranslatedError {
            get {
                return ResourceManager.GetString("NotTranslatedError", resourceCulture);
            }
        }
    }
}
