//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalaryCalculator.Desktop.Ressources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReportTextualRessources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReportTextualRessources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SalaryCalculator.Desktop.Ressources.ReportTextualRessources", typeof(ReportTextualRessources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gross salary:.
        /// </summary>
        public static string GrossSalary {
            get {
                return ResourceManager.GetString("GrossSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hourly rate (gross).
        /// </summary>
        public static string HourlyRateGross {
            get {
                return ResourceManager.GetString("HourlyRateGross", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to net salary:.
        /// </summary>
        public static string NetSalary {
            get {
                return ResourceManager.GetString("NetSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of overtime hours:.
        /// </summary>
        public static string OvertimeHours {
            get {
                return ResourceManager.GetString("OvertimeHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary for the month.
        /// </summary>
        public static string SummaryForTheMonth {
            get {
                return ResourceManager.GetString("SummaryForTheMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time dimension on this date.
        /// </summary>
        public static string TimeDimension {
            get {
                return ResourceManager.GetString("TimeDimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total gross salary (base + overhours):.
        /// </summary>
        public static string TotalGrossSalary {
            get {
                return ResourceManager.GetString("TotalGrossSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total net salary (base + overhours):.
        /// </summary>
        public static string TotalNetSalary {
            get {
                return ResourceManager.GetString("TotalNetSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to working hours.
        /// </summary>
        public static string WorkingHours {
            get {
                return ResourceManager.GetString("WorkingHours", resourceCulture);
            }
        }
    }
}
